server:
  port: 80
spring:
 datasource:
   url: jdbc:mysql://127.0.0.1:3306/family
   username: root
   password: 7777
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl